spring.application.name=backend

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ClearTier
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opcional: Para que no falle si la BD no existe
spring.jpa.generate-ddl=true
