# Servidor
server.port=8081

# PostgreSQL
<<<<<<< HEAD
spring.datasource.url=
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/ClearTier
>>>>>>> feature/cristian
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Google GenAI (Gemini)
spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=

# DevTools
spring.devtools.add-properties=true
spring.devtools.restart.enabled=true

<<<<<<< HEAD
spring.security.user.name=user
spring.security.user.password=en la consola aparecerá el password generado y lo tiene que pegar aquí
=======
spring.security.user.name=
spring.security.user.password=
>>>>>>> feature/cristian
