# Servidor
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ClearTier
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Google GenAI (Gemini)
spring.ai.google.genai.api-key=TU_API_KEY_AQUI
spring.ai.google.genai.chat.options.model=gemini-2.0-flash

# DevTools
spring.devtools.add-properties=true
spring.devtools.restart.enabled=true